<a href="https://colab.research.google.com/github/AKASHPATI007/Pandas-exercise-w3school/blob/main/Pandas_Exercise_W3_school.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# **Pandas Series**

**Ques:-1.** Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

**Ans-** **pd.Series([2, 4, 6, 8, 10])**

**Ques:-2.** Write a Pandas program to convert a Panda module Series to Python list and it's type.

**Ans:- ds = pd.Series([2, 4, 6, 8, 10])--->ds.tolist()**

**Ques:-3.** Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

**Ans:- ds1 = pd.Series([2, 4, 6, 8, 10] and ds2 = pd.Series([1, 3, 5, 7, 9])---> add- ds1+ds2---> sub- ds1-ds2 ---> mult- ds1*ds2 ---> div- ds1/ds2**

**Ques:-4.** Write a Pandas program to compare the elements of the two Pandas Series.

**Ans:- ds1 = pd.Series([2, 4, 6, 8, 10] and ds2 = pd.Series([1, 3, 5, 7, 9])--->equal- ds1 == ds2---> greater- ds1>ds2**

**Ques:-5.** Write a Pandas program to convert a dictionary to a Pandas series.

**Ans:- d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}--->new_series = pd.Series(d1)**

**Ques:-6.** Write a Pandas program to convert a NumPy array to a Pandas series.

**Ans:- np_array = np.array([10, 20, 30, 40, 50])--->new_series = pd.Series(np_array)**

**Ques:-7.** Write a Pandas program to change the data type of given a column or a Series.

**Ans:- s1 = pd.Series(['100', '200', 'python', '300.12', '400'])---> s2 = pd.to_numeric(s1, errors='coerce')**

**Ques:-8.** Write a Pandas program to convert the first column of a DataFrame as a Series.

**Ans:- df.ix[:,0]**

**Ques:-9.** Write a Pandas program to convert a given Series to an array.

**Ans:- s1 = pd.Series(['100', '200', 'python', '300.12', '400'])--->Series_to_array-> a = s1.values**

**Ques:-10.** Write a Pandas program to sort a given Series.

**Ans:-  s = pd.Series(['100', '200', 'python', '300.12', '400'])---> new_s = pd.Series(s).sort_values()**

**Ques:-11.** Write a Pandas program to convert Series of lists to one Series.

**Ans:- s = pd.Series([['Red', 'Green', 'White'],['Red', 'Black']['Yellow']])---> s = s.apply(pd.Series).stack().reset_index(drop=True)**

**Ques:-12.** Write a Pandas program to add some data to an existing Series.

**Ans:- s = pd.Series(['100', '200', 'python', '300.12', '400'])---> new_s = pd.concat([s, pd.Series([500, "php"])], ignore_index=True)**

**Ques:-13.** Write a Pandas program to create a subset of a given series based on value and condition.

**Ans:- s = pd.Series([0,1,2,3,4,5,6,7,8,9,10])---> n = 6--->new_s = s[s < n]**

**Ques:-14.** Write a Pandas program to change the order of index of a given series.

**Ans:- s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])--->After changing order---> s = s.reindex(index = ['B','A','C','D','E'])**

**Ques:-15.** Write a Pandas program to create the mean and standard deviation of the data of a given Series.

**Ans:- s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])--->s.mean()--->s.std()**

**Ques:-16.** Write a Pandas program to get the items of a given series not present in another given series.

**Ans:- sr1 = pd.Series([1, 2, 3, 4, 5]),sr2 = pd.Series([2, 4, 6, 8, 10])---> result = sr1[~sr1.isin(sr2)]**

**Ques:-17.** Write a Pandas program to get the items which are not common of two given series.

**Ans:- sr1 = pd.Series([1, 2, 3, 4, 5]),sr2 = pd.Series([2, 4, 6, 8, 10])--->sr11 = pd.Series(np.union1d(sr1, sr2)),sr22 = pd.Series(np.intersect1d(sr1, sr2))---->result = sr11[~sr11.isin(sr22)]**

**Ques:-18.** Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

**Ans:- num_state = np.random.RandomState(100)--->num_series = pd.Series(num_state.normal(10, 4, 20))---> result = np.percentile(num_series, q=[0, 25, 50, 75, 100])**

**Ques:-19.** Write a Pandas program to calculate the frequency counts of each unique value of a given series.

**Ans:- num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))---> result = num_series.value_counts()**

**Ques:-20.** Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.

**Ans:- num_series = pd.Series(np.random.randint(1, 5, [15]))--->num_series.value_counts()---> result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'**

**Ques:-21.** Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.

**Ans:- num_series = pd.Series(np.random.randint(1, 10, 9))--->result = np.where(num_series % 5==0)**

**Ques:-22.** Write a Pandas program to extract items at given positions of a given series.

**Ans:-num_series = pd.Series(list('2390238923902390239023'))--->element_pos = [0, 2, 6, 11, 21]--->result = num_series.take(element_pos)**

**Ques:-23.** Write a Pandas program to get the positions of items of a given series in another given series.

**Ans:- series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])--->series2 = pd.Series([1, 3, 5, 7, 10])---> result = [pd.Index(series1).get_loc(i) for i in series2]**

**Ques:-24.** Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.

**Ans:- series1 = pd.Series(['php', 'python', 'java', 'c#'])---> result = series1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())**

**Ques:-25.** Write a Pandas program to calculate the number of characters in each word in a given series.

**Ans:- series1 = pd.Series(['Php', 'Python', 'Java', 'C#'])---> result = series1.map(lambda x: len(x))**

**Ques:-26.** Write a Pandas program to compute difference of differences between consecutive numbers of a given series.

**Ans:- series1 = pd.Series([1, 3, 5, 8, 10, 11, 15])---> series1.diff().tolist()---> series1.diff().diff().tolist()**

**Ques:-27.** Write a Pandas program to convert a series of date strings to a timeseries.

**Ans:- date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])----> pd.to_datetime(date_series)**

**Ques:-28.** Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.

**Ans:- from dateutil.parser import parse--->date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])----> date_series = date_series.map(lambda x: parse(x))----> month-> date_series.dt.day.tolist()---> year-> date_series.dt.dayofyear.tolist()---> week-> date_series.dt.weekofyear.tolist()---> Day_of_week-> date_series.dt.weekday_name.tolist()**

**Ques:-29.** Write a Pandas program to convert year-month string to dates adding a specified day of the month.

**Ans:-from dateutil.parser import parse--->date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])---> result = date_series.map(lambda d: parse('11 ' + d))**

**Ques:-30.** Write a Pandas program to filter words from a given series that contain atleast two vowels

**Ans:- from collections import Counter---> color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])---> result =color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)**

**Ques:-31** Write a Pandas program to compute the Euclidean distance between two given series.
Euclidean distance

**Ans:- x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])---> y = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])----> np.linalg.norm(x-y)**

**Ques:-32.** Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.

**Ans:- nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])---> temp = np.diff(np.sign(np.diff(nums)))---> result = np.where(temp == -2)[0] + 1**

**Ques:-33** Write a Pandas program to replace missing white spaces in a given string with the least frequent character.

**Ans:- str1 = 'abc def abcdef icd'--->ser = pd.Series(list(str1))--->
element_freq = ser.value_counts()--->current_freq = element_freq.dropna().index[-1]----> result = "".join(ser.replace(' ', current_freq))**

**Ques:-34.** Write a Pandas program to compute the autocorrelations of a given numeric series.

**Ans:- num_series = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))---> autocorrelations = [num_series.autocorr(i).round(2) for i in range(11)]---> autocorrelations[1:]**

**Ques:-35.** Write a Pandas program to create a TimeSeries to display all the Sundays of given year.

**Ans:- result = pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))**

**Ques:-36.** Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.

**Ans:- char_list = list('ABCDEFGHIJKLMNOP')--->num_arra = np.arange(8)--->num_dict = dict(zip(char_list, num_arra))--->num_ser = pd.Series(num_dict)---> df = num_ser.to_frame().reset_index()**

**Ques:-37.** Write a Pandas program to stack two given series vertically and horizontally.

**Ans:- series1 = pd.Series(range(10))--->series2 = pd.Series(list('pqrstuvwxy'))---> series1.append(series2)---->df = pd.concat([series1, series2], axis=1)**

**Ques:-38.** Write a Pandas program to check the equality of two given series.

**Ans:- nums1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])--->nums2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])--->nums1 == nums2**

**Ques:-39.** Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.

**Ans:- nums = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])---> nums.idxmin()---> nums.idxmax()**

**Ques:- 40.** Write a Pandas program to check inequality over the index axis of a given dataframe and a given series.

**Ans:- df_data = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
sr_data = pd.Series([68, 75, 86, 80, None]) ----> df_data.ne(sr_data, axis = 0)**


#**PANDAS DATAFRAME**

In [ ]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

**Ques:-1.** Write a Pandas program to create a dataframe from a dictionary and display it.

**Ans:- df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})**

**Ques:-2.** Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

**Ans:- exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James','Rajesh'],'score': [12.5, 9, 16.5, np.nan, 9],'attempts': [1, 3, 2, 3, 2],'qualify': ['yes', 'no', 'yes', 'no', 'no']}--->labels = ['a', 'b', 'c', 'd', 'e']--->df = pd.DataFrame(exam_data , index=labels)**

**Ques:-3.** Write a Pandas program to display a summary of the basic information about a specified DataFrame and its data.

**Ans:- df.info()**

**Ques:-4.** Write a Pandas program to get the first 3 rows of a given DataFrame.

**Ans:- df.iloc[:3]**

**Ques:-5.** Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

**Ans:- df[['name', 'score']]**

**Ques:-6.** Write a Pandas program to select the specified columns and rows from a given data frame.

**Ans:- df.iloc[[1, 3, 5, 6], [1, 3]]**--->give (1,2,5,6-rows & 1,3-columns)

**Ques:-7.** Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

**Ans:- df[df['attempts'] > 2]**

**Ques:-8.** Write a Pandas program to count the number of rows and columns of a DataFrame.

**Ans:- total_rows=len(df.axes[0])--->total_cols=len(df.axes[1])**

**Ques:-9.** Write a Pandas program to select the rows where the score is missing, i.e. is NaN.

**Ans:- df[df['score'].isnull()]**

**Ques:-10.** Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).

**Ans:- df[df['score'].between(15, 20)]**

**Ques:-11.** Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

**Ans:- df[(df['attempts'] < 2) & (df['score'] > 15)]**

**Ques:-12.** Write a Pandas program to change the score in row 'd' to 11.5.

**Ans:- df.loc['d', 'score'] = 11.5**

**Ques:-13.** Write a Pandas program to calculate the sum of the examination attempts by the students.

**Ans:- df['attempts'].sum()**

**Ques:-14.** Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.

**Ans:- df['score'].mean()**

**Ques:-15.** Write a Pandas program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.

**Ans:- Append- df.loc['k'] = [1, 'Suresh', 'yes', 15.5]--->Delete new row- df.drop('k')**

**Ques:-16.** Write a Pandas program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.

**Ans:- df.sort_values(by=['name', 'score'], ascending=[False, True])**

**Ques:-17.** Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

**Ans:- df['qualify'] = df['qualify'].map({'yes': True, 'no': False})**

**Ques:-18.** Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

**Ans:- df['name'] = df['name'].replace('James', 'Suresh')**

**Ques:-19.** Write a Pandas program to delete the 'attempts' column from the DataFrame.

**Ans:- df.pop('attempts')**

**Ques:-20.** Write a Pandas program to insert a new column in existing DataFrame.

**Ans:- color = ['Red','Blue','Orange','Red','White','White','Blue','Green','Green','Red']--->df['color'] = color**--->Added new column color to df

**Ques:-21.** Write a Pandas program to iterate over rows in a DataFrame.

**Ans:- exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]--->df = pd.DataFrame(exam_data)--->for index, row in df.iterrows():--->print(row['name'], row['score'])**

**Ques:-22.** Write a Pandas program to get list from DataFrame column headers.

**Ans:- list(df.columns.values)**

**Ques:-23.** Write a Pandas program to rename columns of a given DataFrame

**ans:- df = df.rename(columns={'col1': 'Column1', 'col2': 'Column2', 'col3': 'Column3'})**

**Ques:-24.** Write a Pandas program to select rows from a given DataFrame based on values in some columns.

**Ans:- d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}--->df = pd.DataFrame(data=d)---> df.loc[df['col1'] == 4]**

**Ques:-25.** Write a Pandas program to change the order of a DataFrame columns.

**Ans:- After altering col1 and col3----->df = df[['col3', 'col2', 'col1']]**

**Ques:-26.** Write a Pandas program to add one row in an existing DataFrame.

**Ans:- d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}--->df = pd.DataFrame(data=d)df2 = {'col1': 10, 'col2': 11, 'col3': 12}---->df = df.append(df2, ignore_index=True)**

**Ques:-27.** Write a Pandas program to write a DataFrame to CSV file using tab separator.

**Ans:- d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}--->df = pd.DataFrame(data=d)--->df.to_csv('new_file.csv', sep='\t', index=False)--->new_df = pd.read_csv('new_file.csv')**

**Ques:-28.** Write a Pandas program to count city wise number of people from a given of data set (city, name of the person).

**Ans:- df1 = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']})---->g1 = df1.groupby(["city"]).size().reset_index(name='Number of people')**

**Ques:-29.** Write a Pandas program to delete DataFrame row(s) based on given column value.

**Ans:- df = df[df.col2 != 5]** - delete 2nd row as it contain 5 in column2

**Ques:-30.** Write a Pandas program to widen output display to see more columns.

**Ans:- pd.set_option('display.max_rows', 500) -sets the maximum number of rows that Pandas will display to 500.---->pd.set_option('display.max_columns', 500)- sets the maximum number of columns that Pandas will display to 500.---->pd.set_option('display.width', 1000) -sets the maximum width of the display to 1000 characters.**

**Ques:-31.** Write a Pandas program to select a row of series/dataframe by given integer index.

**Ans:- result = df.iloc[[2]]**-give third row of dataframe as index 2

**Ques:-32.** Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.

**Ans:- df =  df.fillna(0)**

**Ques:-33.** Write a Pandas program to convert index in a column of the given dataframe.

**Ans:-** After converting index in a column---->**df.reset_index(level=0, inplace=True)**--->Hiding index---> **df.to_string(index=False)**

**Ques:-34.** Write a Pandas program to set a given value for particular cell in  DataFrame using index value.

**Ans:- df.set_value(8, 'score', 10.2)**---> The set_value() function is used to modify the value of the cell in the 8th row and 'score' column to 10.2.

**Ques:-35.** Write a Pandas program to count the NaN values in one or more columns in DataFrame.

**Ans:- df.isnull().values.sum()**

**Ques:-36.** Write a Pandas program to drop a list of rows from a specified DataFrame.

**Ans:- df = df.drop(df.index[[2,4]])**--->removed 2nd & 4th rows

**Ques:-37.** Write a Pandas program to reset index in a given DataFrame.

**Ans:- df = df.drop([0, 1])**--> This code drops the rows with index 0 and 1 **df = df.reset_index()**---> This code resets the index using the reset_index() method, which creates a new column called "index" with the index values before resetting.

**Ques:-38.** Write a Pandas program to divide a DataFrame in a given ratio.

**Ans:- df = pd.DataFrame(np.random.randn(10, 2))--->part_70 = df.sample(frac=0.7,random_state=10)--->part_30 = df.drop(part_70.index)**---> creates a new DataFrame 'part_70' by sampling 70% of the rows from 'df' using the sample method. The 'frac' parameter specifies the fraction of the rows to be sampled, while the random_state parameter is used to ensure that the same set of rows is always sampled if the code is run again with the same random_state value.

**Ques:-39.** Write a Pandas program to combining two series into a DataFrame.

**Ans:- s1 = pd.Series(['100', '200', 'python', '300.12', '400'])--->s2 = pd.Series(['10', '20', 'php', '30.12', '40'])--->df = pd.concat([s1, s2], axis=1)**---> resulting DataFrame will have 5 rows and 2 columns.

**Ques:-40.** Write a Pandas program to shuffle a given DataFrame rows.

**Ans:- df = df.sample(frac=1)**--->sample method is used to shuffle the rows of this DataFrame in a random order--->frac=0.5 so half rows. frac=2 so double rows means earlier 4 then this time will 8.

**Ques:-41.** Write a Pandas program to convert DataFrame column type from string to datetime.

**Ans:- s = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'])---->r = pd.to_datetime(pd.Series(s))--->df = pd.DataFrame(r)**

**Ques:-42.** Write a Pandas program to rename a specific column name in a given DataFrame.

**Ans:- df=df.rename(columns = {'col2':'Column2'})**

**Ques:-43.** Write a Pandas program to get a list of a specified column of a DataFrame.

**Ans:- col2_list = df["col2"].tolist()**

**Ques:-44.** Write a Pandas program to create a DataFrame from a Numpy array and specify the index column and column headers.

**Ans:- dtype = [('Column1','int32'), ('Column2','float32'), ('Column3','float32')]--->values = numpy.zeros(15, dtype=dtype)--->index = ['Index'+str(i) for i in range(1, len(values)+1)]--->df = pandas.DataFrame(values, index=index)**

**Ques:-45.** Write a Pandas program to find the row for where the value of a given column is maximum.

**Ans:- df['col1'].argmax()**

**Ques:-46.** Write a Pandas program to check whether a given column is present in a DataFrame or not.

**Ans:- if 'col4' in df.columns:
  print("Col4 is present in DataFrame.")
else:
  print("Col4 is not present in DataFrame.")**

**Ques:-47.** Write a Pandas program to get the specified row value of a given DataFrame.

**Ans:-df.iloc[0]--row1---> df.iloc[3]--row4**

**Ques:-48.** Write a Pandas program to get the datatypes of columns of a DataFrame.

**Ans:- df.dtypes**

**Ques:-49.** Write a Pandas program to append data to an empty DataFrame.

**Ans:- df = pd.DataFrame()--->data = pd.DataFrame({"col1": range(3),"col2": range(3)})--->print("After appending some data:")--->df = df.append(data)**

**Ques:-50.** Write a Pandas program to sort a given DataFrame by two or more columns.

**Ans:- df = df.sort_values(['attempts', 'name'], ascending=[True, True])**

**Ques:-51.** Write a Pandas program to convert the datatype of a given column (floats to ints).

**Ans:- df.score = df.score.astype(int)**--->Data type of 'score' column from float to int

**Ques:-52.** Write a Pandas program to remove infinite values from a given DataFrame.

**Ans:- df = pd.DataFrame([1000, 2000, 3000, -4000, np.inf, -np.inf])--->df = df.replace([np.inf, -np.inf], np.nan)**

**Ques:-53**  Write a Pandas program to insert a given column at a specific column index in a DataFrame.

**Ans:- d = {'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}--->new_col = [1, 2, 3, 4, 7]--->df.insert(loc=0, column='col1', value=new_col)**---loc=0 means 1st column

**Ques:-54**  Write a Pandas program to convert a given list of lists into a Dataframe.

**Ans:- my_lists = [['col1', 'col2'], [2, 4], [1, 3]]---.# sets the headers as list--->headers = my_lists.pop(0) --->df = pd.DataFrame(my_lists, columns = headers)**--give header as column

**Ques:-55** Write a Pandas program to group by the first column and get second column as lists in rows.

**Ans:- df = pd.DataFrame( {'col1':['C1','C1','C2','C2','C2','C3','C2'], 'col2':[1,2,3,3,4,6,5]})----> df = df.groupby('col1')['col2'].apply(list)**

**Ques:-56** Write a Pandas program to get column index from column name of a given DataFrame.

**Ans:- d = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}---->df.columns.get_loc("col2")**

**Ques:-57** Write a Pandas program to count number of columns of a DataFrame.

**Ans:-len(df.columns)**

**Ques:-58** Write a Pandas program to select all columns, except one given column in a DataFrame.

**Ans:- df = df.loc[:, df.columns != 'col3']**

**Ques:-59** Write a Pandas program to get first n records of a DataFrame.

**Ans:- df.head(3)**

**Ques:-60**  Write a Pandas program to get last n records of a DataFrame.

**Ans:- df.tail(3)**

**Ques:-61** Write a Pandas program to get topmost n records within each group of a DataFrame.

**Ans:- df1 = df.nlargest(3, 'col1')--->df1 = df.nlargest(3, 'col2')--->df1 = df.nlargest(3, 'col3')**

**Ques:-62** Write a Pandas program to remove first n rows of a given DataFrame.

**Ans:- df1 = df.iloc[3:]**

**Ques:-63** Write a Pandas program to remove last n rows of a given DataFrame.

**Ans:- df1 = df.iloc[:3]**

**Ques:-64** Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.

**Ans:- df = pd.DataFrame({'W':[68,75,86,80,66],'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})--->df.add_prefix("A_")--->df.add_suffix("_1")**--> it will give A_W for prefix and W_1 for suffix

**Ques:-65** Write a Pandas program to reverse order (rows, columns) of a given DataFrame.

**Ans:-** reverse column--> **df.loc[:, ::-1]** reverse row--> **df.loc[::-1]**-->Reverse row order and reset index--->**df.loc[::-1].reset_index(drop = True)**

**Ques:-66.**  Write a Pandas program to select columns by data type of a given DataFrame.

**Ans:-** for numeriacal-->**df.select_dtypes(include = "number")**---> for string--> **df.select_dtypes(include = "object")**

**Ques:-67.** Write a Pandas program to split a given DataFrame into two random subsets.

**Ans:- df = pd.DataFrame({'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],'date_of_birth': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],'age': ['18', '21', '22', '22', '23']})-----> df_1 = df.sample(frac = 0.6)--->df_2 = df.drop(df_1.index)**

**Ques:-68.**  Write a Pandas program to rename all columns with the same pattern of a given DataFrame.

**Ans:- df.columns = df.columns.str.lower().str.rstrip()**--->Remove trailing (at the end) whitesapce and convert to lowercase of the columns name

**Ques:-70.** Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.

**Ans:- df = pd.DataFrame({'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton', 'Kierra Gentry'],'age': [18, 22, 85, 50, 80, 5]})-----df["age_groups"] = pd.cut(df["age"], bins = [0, 18, 65, 99], labels = ["kids", "adult", "elderly"])**

**Ques:-72.**  Write a Pandas program to combine many given series to create a DataFrame.

**Ans:-** **sr1 = pd.Series(['php', 'python', 'java', 'c#', 'c++'])---sr2 = pd.Series([1, 2, 3, 4, 5])**----**ser_df = pd.DataFrame(sr1, sr2).reset_index()**-->Combine above series to a dataframe-- **pd.concat([sr1, sr2], axis = 1)**-->Using pandas concat--**pd.DataFrame({"col1":sr1, "col2":sr2})**-->Using pandas DataFrame with a dictionary, gives a specific name to the columns

**Ques:-74.** Write a Pandas program to fill missing values in time series data.

From Wikipedia , in the mathematical field of numerical analysis, **interpolation** is a type of estimation, a method of constructing new data points within the range of a discrete set of known data points.

**Ans:- sdata = {"c1":[120, 130 ,140, 150, np.nan, 170], "c2":[7, np.nan, 10, np.nan, 5.5, 16.5]}---df = pd.DataFrame(sdata)---df.index = pd.util.testing.makeDateIndex()[0:6]----df.interpolate()**

**Ques:-76.** Write a Pandas program to clean object column with mixed data of a given DataFrame using regular expression.

**Ans:- d = {"agent": ["a001", "a002", "a003", "a003", "a004"], "purchase":[4500.00, 7500.00, "$3000.25", "$1250.35", "9000.00"]}---df = pd.DataFrame(d)----df["purchase"] = df["purchase"].replace("[$,]", "", regex = True).astype("float")**

**Ques:-77** Write a Pandas program to get the numeric representation of an array by identifying distinct values of a given column of a DataFrame.

**Ans:- df = pd.DataFrame({'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill'],'Date_Of_Birth ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],'Age': [18.5, 21.2, 22.5, 22, 23]----label1, unique1 = pd.factorize(df['Name'])---print(label1)---print(unique1)**

**Ques:-79**Write a Pandas program to create a DataFrame from the clipboard (data from an Excel spreadsheet or a Google Sheet).

**Ans:- df = pd.read_clipboard()**

**Ques:-80.** Write a Pandas program to check for inequality of two given DataFrames.

**Ans:- df1 = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,85,None,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});---df2 = pd.DataFrame({'W':[78,75,86,80,None],'X':[78,85,96,80,76], 'Y':[84,84,89,83,86],'Z':[86,97,96,72,83]});---df1.ne(df2)**

**Ques:-81.** Write a Pandas program to get lowest n records within each group of a given DataFrame.

**Ans:- d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}---df1 = df.nsmallest(3, 'col1')---df1 = df.nsmallest(3, 'col2')---df1 = df.nsmallest(3, 'col3')**





#**Pandas Joining and merging DataFrame-**

In [ ]:
import pandas as pd
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
        'marks': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'exam_id': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

print("Original DataFrames:")
print(student_data1)
print(student_data2)
print(exam_data)

Original DataFrames:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201
   student_id  exam_id
0          S1       23
1          S2       45
2          S3       12
3          S4       67
4          S5       21
5          S7       55
6          S8       33
7          S9       14
8         S10       56
9         S11       83
10        S12       88
11        S13       12


**Ques:-1.** Write a Pandas program to join the two given dataframes along rows and assign all data.

**Ans:- result_data = pd.concat([student_data1, student_data2])**

**Ques:-2.** Write a Pandas program to join the two given dataframes along columns and assign all data.

**Ans:- result_data = pd.concat([student_data1, student_data2], axis = 1)**

**Ques:-3.** Write a Pandas program to append rows to an existing DataFrame and display the combined data.

**Ans:-** new row-- **s6 = pd.Series(['S6', 'Scarlette Fisher', 205], index=['student_id', 'name', 'marks'])**----**combined_data = student_data1.append(s6, ignore_index = True)**

**Ques:-4** Write a Pandas program to append a list of dictioneries or series to a existing DataFrame and display the combined data.

**Ans:- dicts = [{'student_id': 'S6', 'name': 'Scarlette Fisher', 'marks': 203}, {'student_id': 'S7', 'name': 'Bryce Jensen', 'marks': 207}]---combined_data =  student_data1.append(dicts, ignore_index=True, sort=False)**

**Ques:-5.** Write a Pandas program to join the two given dataframes along rows and merge with another dataframe along the common column id.

**Ans:-** Join first two said dataframes along rows---**result_data = pd.concat([student_data1, student_data2])**---Now join the said result_data and df_exam_data along student_id---**final_merged_data = pd.merge(result_data, exam_data, on='student_id')**

**Ques:-6.**  Write a Pandas program to join the two dataframes using the common column of both dataframes.

**Ans:- merged_data = pd.merge(student_data1, student_data2, on='student_id', how='inner')**

**Ques:-7.** Write a Pandas program to join the two dataframes with matching records from both sides where available.

**Ans:- merged_data = pd.merge(student_data1, student_data2, on='student_id', how='outer')**



In [ ]:
import pandas as pd
data1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'P': ['P0', 'P1', 'P2', 'P3'],
                     'Q': ['Q0', 'Q1', 'Q2', 'Q3']})
data2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'R': ['R0', 'R1', 'R2', 'R3'],
                      'S': ['S0', 'S1', 'S2', 'S3']})
print("Original DataFrames:")
print(data1)
print("--------------------")
print(data2)

Original DataFrames:
  key1 key2   P   Q
0   K0   K0  P0  Q0
1   K0   K1  P1  Q1
2   K1   K0  P2  Q2
3   K2   K1  P3  Q3
--------------------
  key1 key2   R   S
0   K0   K0  R0  S0
1   K1   K0  R1  S1
2   K1   K0  R2  S2
3   K2   K0  R3  S3


**Ques:-8** Write a Pandas program to join (left join) the two dataframes using keys from left dataframe only.

**Ans:-** Merged Data (keys from data1)---**merged_data = pd.merge(data1, data2, how='left', on=['key1', 'key2'])***---Merged Data (keys from data2)---**merged_data = pd.merge(data2, data1, how='left', on=['key1', 'key2'])**

**Ques:-9**  Write a Pandas program to join two dataframes using keys from right dataframe only.

**Ans:-** Merged Data (keys from data2)---**merged_data = pd.merge(data1, data2, how='right', on=['key1', 'key2'])**----Merged Data (keys from data1)---**merged_data = pd.merge(data2, data1, how='right', on=['key1', 'key2'])**

**Ques:-10.** Write a Pandas program to merge two given datasets using multiple join keys.

**Ans:- merged_data = pd.merge(data1, data2, on=['key1', 'key2'])**

**Ques:-11.** Write a Pandas program to create a new DataFrame based on existing series, using specified argument and override the existing columns names.

**Ans:- s1 = pd.Series([0, 1, 2, 3], name='col1')---s2 = pd.Series([0, 1, 2, 3])---s3 = pd.Series([0, 1, 4, 5], name='col3')---df = pd.concat([s1, s2, s3], axis=1, keys=['column1', 'column2', 'column3'])**

**Ques:-12.** Write a Pandas program to create a combination from two dataframes where a column id combination appears more than once in both dataframes.

**Ans:-** Merged Data (many-to-many join case)---result = **pd.merge(data1, data2, on='key1')**



In [ ]:
data1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                      'B': ['B0', 'B1', 'B2']},
                     index=['K0', 'K1', 'K2'])

data2 = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                      'D': ['D0', 'D2', 'D3']},
                     index=['K0', 'K2', 'K3'])

print("Original DataFrames:")
print(data1)
print("--------------------")
print(data2)

Original DataFrames:
     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
--------------------
     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3


**Ques:-13.** Write a Pandas program to combine the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

**Ans:- result = data1.join(data2)**

**Ques:-14.**  Write a Pandas program to merge two given dataframes with different columns.

**Ans:- result = pd.concat([data1,data2], axis=0, ignore_index=True)**

**Ques:-15.** Write a Pandas program to Combine two DataFrame objects by filling null values in one DataFrame with non-null values from other DataFrame.

**Ans:- df1 = pd.DataFrame({'A': [None, 0, None], 'B': [3, 4, 5]})---df2 = pd.DataFrame({'A': [1, 1, 3], 'B': [3, None, 3]})---result = df1.combine_first(df2)**

#**Pandas Grouping and Aggregating-**

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
student_data = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth ': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': [12, 12, 13, 13, 14, 12],
    'height': [173, 192, 186, 167, 151, 159],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4']},
    index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6'])

print("Original DataFrame:")
print(student_data)

Original DataFrame:
   school_code class            name date_Of_Birth   age  height  weight  \
S1        s001     V  Alberto Franco     15/05/2002   12     173      35   
S2        s002     V    Gino Mcneill     17/05/2002   12     192      32   
S3        s003    VI     Ryan Parkes     16/02/1999   13     186      33   
S4        s001    VI    Eesha Hinton     25/09/1998   13     167      30   
S5        s002     V    Gino Mcneill     11/05/2002   14     151      31   
S6        s004    VI    David Parkes     15/09/1997   12     159      32   

    address  
S1  street1  
S2  street2  
S3  street3  
S4  street1  
S5  street2  
S6  street4  


**Ques:-1.** Write a Pandas program to split the following dataframe into groups based on school code. Also check the type of GroupBy object.

**Ans:- result = student_data.groupby(['school_code'])--for name,group in result:--print(name)---print(group)**---Type of the object--**type(result)**

**Ques:-2.** Write a Pandas program to split the following dataframe by school code and get mean, min, and max value of age for each school.

**Ans:- grouped_single = student_data.groupby('school_code').agg({'age': ['mean', 'min', 'max']})**

**Ques:-4.** Write a Pandas program to split the following given dataframe into groups based on single column and multiple columns. Find the size of the grouped data.

**Ans:-** Split the said data on school_code wise---**grouped_single = student_data.groupby(['school_code'])**---Size of the grouped data - single column---**grouped_single.size()**---Split the said data on school_code and class wise---**grouped_mul = student_data.groupby(['school_code', 'class'])**---Size of the grouped data - multiple columns---**grouped_mul.size()**

**Ques:-6.** Write a Pandas program to split the following given dataframe into groups based on school code and call a specific group with the name of the group.

**Ans:-** Split the said data on school_code wise--**grouped = student_data.groupby(['school_code'])**---Call school code 's001'---**grouped.get_group('s001')**


In [ ]:
import pandas as pd
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
orders_data = pd.DataFrame({
'ord_no':[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10','2012-10-05','2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3005,3001,3002,3009,3005,3007,3002,3004,3009,3008,3003,3002],
'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5006,5003,5002,5007,5001]})
print("Original Orders DataFrame:")
print(orders_data)

Original Orders DataFrame:
    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5006
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5007
11   70013    3045.60  2012-04-25         3002         5001


**Ques:-7.** Write a Pandas program to split a dataset, group by one column and get mean, min, and max values by group. Using the following dataset find the mean, min, and max values of purchase amount (purch_amt) group by customer id (customer_id).

**Ans:- result = orders_data.groupby('customer_id').agg({'purch_amt': ['mean', 'min', 'max']})**

**Ques:-8.** Write a Pandas program to split a dataset to group by two columns and count by each row.

**Ans:-** Group by two columns and count by each row---**result = orders_data.groupby(['salesman_id','customer_id']).size().reset_index().groupby(['salesman_id','customer_id'])[[0]].max()**

**Ques:-9.** Write a Pandas program to split a dataset to group by two columns and then sort the aggregated results within the groups.
In the following dataset group on 'customer_id', 'salesman_id' and then sort sum of purch_amt within the groups.

**Ans:- **df_agg = df.groupby(['customer_id','salesman_id']).agg({'purch_amt':sum})---result = df_agg['purch_amt'].groupby(level=0, group_keys=False)**----**result.nlargest()**

**Ques:-10.** Write a Pandas program to split the following dataframe into groups based on customer id and create a list of order date for each group.

**Ans:- result = df.groupby('customer_id')['ord_date'].apply(list)**

**Ques:-11.** Write a Pandas program to split the following dataframe into groups and calculate monthly purchase amount.

**Ans:- df['ord_date']= pd.to_datetime(df['ord_date'])**---Month wise purchase amount---**result = df.set_index('ord_date').groupby(pd.Grouper(freq='M')).agg({'purch_amt':sum})**

**Ques:-12.** Write a Pandas program to split the following dataframe into groups, group by month and year based on order date and find the total purchase amount year wise, month wise.

**Ans:- df['ord_date']= pd.to_datetime(df['ord_date'])**----**result = df.groupby([df['ord_date'].dt.year, df['ord_date'].dt.month]).agg({'purch_amt':sum})**

**Ques:-13.** Write a Pandas program to split the following dataframe into groups based on first column and set other column values into a list of values.

**Ans:- df = pd.DataFrame( {'X' : [10, 10, 10, 20, 30, 30, 10], 'Y' : [10, 15, 11, 20, 21, 12, 14], 'Z' : [22, 20, 18, 20, 13, 10, 0]})------result= df.groupby('X').aggregate(lambda tdf: tdf.unique().tolist())**

**Ques:-14.** Write a Pandas program to split the following dataframe into groups and count unique values of 'value' column.

**Ans:- df = pd.DataFrame({'id': [1, 1, 2, 3, 3, 4, 4, 4],'value': ['a', 'a', 'b', None, 'a', 'a', None, 'b']------df.groupby('value')['id'].nunique()**

**Ques:-15.** Write a Pandas program to split the following dataframe into groups based on all columns and calculate Groupby value counts on the dataframe.

**Ans:- df = pd.DataFrame( {'id' : [1, 2, 1, 1, 2, 1, 2], 'type' : [10, 15, 11, 20, 21, 12, 14], 'book' : ['Math','English','Physics','Math','English','Physics','English']})---->result = df.groupby(['id', 'type', 'book']).size().unstack(fill_value=0)**

**Ques:-16.** Write a Pandas program to split a given dataframe into groups and list all the keys from the GroupBy object.

**Ans:- gp = df.groupby('school_code')---->gp.groups.keys()**

**Ques:-17.** Write a Pandas program to split a given dataframe into groups and create a new column with count from GroupBy.

**Ans:- df = pd.DataFrame({'book_name':['Book1','Book2','Book3','Book4','Book1','Book2','Book3','Book5'],'book_type':['Math','Physics','Computer','Science','Math','Physics','Computer','English'],'book_id':[1,2,3,4,1,2,3,5]})-----result = df.groupby(["book_name", "book_type"])["book_type"].count().reset_index(name="count")**

**Ques:-18.** Write a Pandas program to split a given dataframe into groups with bin counts.

**Ans:- groups = df.groupby(['customer_id', pd.cut(df.sales_id, 3)])
result = groups.size().unstack()**




In [ ]:
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s001'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth ': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': [12, 12, 13, 13, 14, 12],
    'height': [173, 192, 186, 167, 151, 159],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4']},
    index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6'])
print("Original DataFrame:")
print(df)

Original DataFrame:
   school_code class            name date_Of_Birth   age  height  weight  \
S1        s001     V  Alberto Franco     15/05/2002   12     173      35   
S2        s002     V    Gino Mcneill     17/05/2002   12     192      32   
S3        s003    VI     Ryan Parkes     16/02/1999   13     186      33   
S4        s001    VI    Eesha Hinton     25/09/1998   13     167      30   
S5        s002     V    Gino Mcneill     11/05/2002   14     151      31   
S6        s001    VI    David Parkes     15/09/1997   12     159      32   

    address  
S1  street1  
S2  street2  
S3  street3  
S4  street1  
S5  street2  
S6  street4  


**Ques:-19.** Write a Pandas program to split a given dataframe into groups with multiple aggregations.Split the following given dataframe by school code, class and get mean, min, and max value of height and age for each value of the school.

**Ans:- result = df.groupby(['school_code','class']).agg({'height': ['max', 'mean'],'weight': ['sum','min','count']})**

In [ ]:
'''Ques:-20:-Write a Pandas program to split a given dataframe into groups and display target column as a list of unique values.'''

df = pd.DataFrame( {'id' : ['A','A','A','A','A','A','B','B','B','B','B'],
                    'type' : [1,1,1,1,2,2,1,1,1,2,2],
                    'book' : ['Math','Math','English','Physics','Math','English','Physics','English','Physics','English','English']})

print("Original DataFrame:")
print(df)
new_df = df[['id', 'type', 'book']].drop_duplicates()\
                         .groupby(['id','type'])['book']\
                         .apply(list)\
                         .reset_index()

new_df['book'] = new_df.apply(lambda x: (','.join([str(s) for s in x['book']])), axis = 1)
print("\nList all unique values in a group:")
print(new_df)

Original DataFrame:
   id  type     book
0   A     1     Math
1   A     1     Math
2   A     1  English
3   A     1  Physics
4   A     2     Math
5   A     2  English
6   B     1  Physics
7   B     1  English
8   B     1  Physics
9   B     2  English
10  B     2  English

List all unique values in a group:
  id  type                  book
0  A     1  Math,English,Physics
1  A     2          Math,English
2  B     1       Physics,English
3  B     2               English


**Ques:-20.** Write a Pandas program to split a given dataframe into groups and display target column as a list of unique values.

**Ans:- df = pd.DataFrame( {'id' : ['A','A','A','A','A','A','B','B','B','B','B'], 'type' : [1,1,1,1,2,2,1,1,1,2,2], 'book' : ['Math','Math','English','Physics','Math','English','Physics','English','Physics','English','English']})----->new_df = df[['id', 'type', 'book']].drop_duplicates().groupby(['id','type'])['book'].apply(list).reset_index()----->new_df['book'] = new_df.apply(lambda x: (','.join([str(s) for s in x['book']])), axis = 1)---->print(new_df)**




In [2]:
import pandas as pd
df = pd.DataFrame({
'ord_no':[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['05-10-2012','09-10-2012','05-10-2012','08-17-2012','10-09-2012','07-27-2012','10-09-2012','10-10-2012','10-10-2012','06-17-2012','07-08-2012','04-25-2012'],
'customer_id':[3001,3001,3005,3001,3005,3001,3005,3001,3005,3001,3005,3005],
'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5006,5003,5002,5007,5001]})
print("Original Orders DataFrame:")
print(df)

Original Orders DataFrame:
    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  05-10-2012         3001         5002
1    70009     270.65  09-10-2012         3001         5005
2    70002      65.26  05-10-2012         3005         5001
3    70004     110.50  08-17-2012         3001         5003
4    70007     948.50  10-09-2012         3005         5002
5    70005    2400.60  07-27-2012         3001         5001
6    70008    5760.00  10-09-2012         3005         5001
7    70010    1983.43  10-10-2012         3001         5006
8    70003    2480.40  10-10-2012         3005         5003
9    70012     250.45  06-17-2012         3001         5002
10   70011      75.29  07-08-2012         3005         5007
11   70013    3045.60  04-25-2012         3005         5001


**Ques:-21.** Write a Pandas program to split the following dataframe into groups and calculate quarterly purchase amount.

**Ans:- df['ord_date']= pd.to_datetime(df['ord_date'])---->result = df.set_index('ord_date').groupby(pd.Grouper(freq='Q')).agg({'purch_amt':sum})**



In [4]:
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
student_data = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth ': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': [12, 12, 13, 13, 14, 12],
    ' height ': [173, 192, 186, 167, 151, 159],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4']},
    index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6'])

print(student_data)

   school_code class            name date_Of_Birth   age   height   weight  \
S1        s001     V  Alberto Franco     15/05/2002   12       173      35   
S2        s002     V    Gino Mcneill     17/05/2002   12       192      32   
S3        s003    VI     Ryan Parkes     16/02/1999   13       186      33   
S4        s001    VI    Eesha Hinton     25/09/1998   13       167      30   
S5        s002     V    Gino Mcneill     11/05/2002   14       151      31   
S6        s004    VI    David Parkes     15/09/1997   12       159      32   

    address  
S1  street1  
S2  street2  
S3  street3  
S4  street1  
S5  street2  
S6  street4  


**Ques:-22.**  Write a Pandas program to split the following dataframe into groups by school code and get mean, min, and max value of age with customized column name for each school.

**Ans:- grouped_single = student_data.groupby('school_code').agg(Age_Mean = ('age','mean'),Age_Max=('age',max),Age_Min=('age',min))**



In [5]:
df = pd.DataFrame({
'ord_no':[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
'purch_amt':[150.5, 270.65, 65.26, 110.5, 948.5, 2400.6, 5760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'ord_date': ['05-10-2012','09-10-2012','05-10-2012','08-17-2012','10-09-2012','07-27-2012','10-09-2012','10-10-2012','10-10-2012','06-17-2012','07-08-2012','04-25-2012'],
'customer_id':['C3001','C3001','D3005','D3001','C3005','D3001','C3005','D3001','D3005','C3001','D3005','D3005'],
'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5006,5003,5002,5007,5001]})
print("Original Orders DataFrame:")
print(df)

Original Orders DataFrame:
    ord_no  purch_amt    ord_date customer_id  salesman_id
0    70001     150.50  05-10-2012       C3001         5002
1    70009     270.65  09-10-2012       C3001         5005
2    70002      65.26  05-10-2012       D3005         5001
3    70004     110.50  08-17-2012       D3001         5003
4    70007     948.50  10-09-2012       C3005         5002
5    70005    2400.60  07-27-2012       D3001         5001
6    70008    5760.00  10-09-2012       C3005         5001
7    70010    1983.43  10-10-2012       D3001         5006
8    70003    2480.40  10-10-2012       D3005         5003
9    70012     250.45  06-17-2012       C3001         5002
10   70011      75.29  07-08-2012       D3005         5007
11   70013    3045.60  04-25-2012       D3005         5001


**Ques:-23.** Write a Pandas program to split the following datasets into groups on customer id and calculate the number of customers starting with 'C', the list of all products and the difference of maximum purchase amount and minimum purchase amount

**Ans:- def customer_id_C(x):---return (x.str[0] == 'C').sum()---->result = df.groupby(['salesman_id']).agg(customer_id_start_C = ('customer_id', customer_id_C),customer_id_list = ('customer_id', lambda x: ', '.join(x)),purchase_amt_gap   = ('purch_amt', lambda x: x.max()-x.min()))--->result**

**Ques:-24.** Write a Pandas program to split the following datasets into groups on customer_id to summarize purch_amt and calculate percentage of purch_amt in each group.

**Ans:- gr_data = df.groupby(['customer_id','salesman_id']).agg({'purch_amt': 'sum'})--gr_data["% (Purch Amt.)"] = gr_data.apply(lambda x:  100*x / x.sum())---->gr_data**



In [7]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth ': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': [12, 12, 13, 13, 14, 12],
    'height': [173, 192, 186, 167, 151, 159],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4']},
    index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6'])

print(df)

   school_code class            name date_Of_Birth   age  height  weight  \
S1        s001     V  Alberto Franco     15/05/2002   12     173      35   
S2        s002     V    Gino Mcneill     17/05/2002   12     192      32   
S3        s003    VI     Ryan Parkes     16/02/1999   13     186      33   
S4        s001    VI    Eesha Hinton     25/09/1998   13     167      30   
S5        s002     V    Gino Mcneill     11/05/2002   14     151      31   
S6        s004    VI    David Parkes     15/09/1997   12     159      32   

    address  
S1  street1  
S2  street2  
S3  street3  
S4  street1  
S5  street2  
S6  street4  


**Ques:-25.** Write a Pandas program to split a dataset, group by one column and get mean, min, and max values by group, also change the column name of the aggregated metric. Using the following dataset find the mean, min, and max values of purchase amount (purch_amt) group by customer id (customer_id).

**Ans:- grouped_single = df.groupby('school_code').agg({'age': [("mean_age","mean"), ("min_age", "min"), ("max_age","max")]})**



In [8]:
# **Ques:-26.** Write a Pandas program to split a given dataset, group by two columns and
# convert other columns of the dataframe into a dictionary with column header as key.

print("Original DataFrame:")
print(df)
dict_data_list = list()

for gg, dd in df.groupby(['school_code','class']):
    group = dict(zip(['school_code','class'], gg))
    ocolumns_list = list()
    for _, data in dd.iterrows():
        data = data.drop(labels=['school_code','class'])
        ocolumns_list.append(data.to_dict())
    group['other_columns'] = ocolumns_list
    dict_data_list.append(group)

print(dict_data_list)


Original DataFrame:
   school_code class            name date_Of_Birth   age  height  weight  \
S1        s001     V  Alberto Franco     15/05/2002   12     173      35   
S2        s002     V    Gino Mcneill     17/05/2002   12     192      32   
S3        s003    VI     Ryan Parkes     16/02/1999   13     186      33   
S4        s001    VI    Eesha Hinton     25/09/1998   13     167      30   
S5        s002     V    Gino Mcneill     11/05/2002   14     151      31   
S6        s004    VI    David Parkes     15/09/1997   12     159      32   

    address  
S1  street1  
S2  street2  
S3  street3  
S4  street1  
S5  street2  
S6  street4  
[{'school_code': 's001', 'class': 'V', 'other_columns': [{'name': 'Alberto Franco', 'date_Of_Birth ': '15/05/2002', 'age': 12, 'height': 173, 'weight': 35, 'address': 'street1'}]}, {'school_code': 's001', 'class': 'VI', 'other_columns': [{'name': 'Eesha Hinton', 'date_Of_Birth ': '25/09/1998', 'age': 13, 'height': 167, 'weight': 30, 'address': 'st

In [9]:
# Write a Pandas program to split a given dataset,
#group by one column and apply an aggregate function to few columns and another aggregate function to the rest of the columns of the dataframe.

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.DataFrame({
'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5006,5003,5002,5007,5001],
'sale_jan':[150.5, 270.65, 65.26, 110.5, 948.5, 2400.6, 1760, 2983.43, 480.4,  1250.45, 75.29,1045.6],
'sale_feb':[250.5, 170.65, 15.26, 110.5, 598.5, 1400.6, 2760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_mar':[150.5, 270.65, 65.26, 110.5, 948.5, 2400.6, 5760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_apr':[150.5, 270.65, 95.26, 210.5, 948.5, 2400.6, 760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_may':[130.5, 270.65, 65.26, 310.5, 948.5, 2400.6, 760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_jun':[150.5, 270.65, 45.26, 110.5, 948.5, 3400.6, 5760, 983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_jul':[950.5, 270.65, 65.26, 210.5, 948.5, 2400.6, 5760, 983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_aug':[150.5, 70.65,  65.26, 110.5, 948.5, 400.6, 5760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_sep':[150.5, 270.65, 65.26, 110.5, 948.5, 200.6, 5760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_oct':[150.5, 270.65, 65.26, 110.5, 948.5, 2400.6, 5760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_nov':[150.5, 270.65, 95.26, 110.5, 948.5, 2400.6, 5760, 1983.43, 2480.4, 250.45, 75.29, 3045.6],
'sale_dec':[150.5, 70.65, 65.26, 110.5, 948.5, 2400.6, 5760, 1983.43, 2480.4, 250.45, 75.29, 3045.6]
})
print("Original Orders DataFrame:")
print(df)
print("\Result after group on salesman_id and apply different aggregate functions:")
df = df.groupby('salesman_id').agg(lambda x : x.sum() if x.name in ['sale_jan','sale_feb','sale_mar'] else x.mean())
print(df)

Original Orders DataFrame:
    salesman_id  sale_jan  sale_feb  sale_mar  sale_apr  sale_may  sale_jun  \
0          5002    150.50    250.50    150.50    150.50    130.50    150.50   
1          5005    270.65    170.65    270.65    270.65    270.65    270.65   
2          5001     65.26     15.26     65.26     95.26     65.26     45.26   
3          5003    110.50    110.50    110.50    210.50    310.50    110.50   
4          5002    948.50    598.50    948.50    948.50    948.50    948.50   
5          5001   2400.60   1400.60   2400.60   2400.60   2400.60   3400.60   
6          5001   1760.00   2760.00   5760.00    760.00    760.00   5760.00   
7          5006   2983.43   1983.43   1983.43   1983.43   1983.43    983.43   
8          5003    480.40   2480.40   2480.40   2480.40   2480.40   2480.40   
9          5002   1250.45    250.45    250.45    250.45    250.45    250.45   
10         5007     75.29     75.29     75.29     75.29     75.29     75.29   
11         5001   1045.60

**Ques:-28.** Write a Pandas program to split a given dataset, group by one column and remove those groups if all the values of a specific columns are not available.

**Ans:-** Group by one column and remove those groups if all the values of a specific columns are not available---**result = df[(~df['height'].isna()).groupby(df['school_code']).transform('any')]**

**Ques:-29.** Write a Pandas program to split a given dataset using group by on specified column into two labels and ranges.
Split the group on 'salesman_id',
Ranges:
1) (5001...5006)
2) (5007..5012)

**Ans:- df = pd.DataFrame({'salesman_id': [5001,5002,5003,5004,5005,5006,5007,5008,5009,5010,5011,5012],'sale_jan':[150.5, 270.65, 65.26, 110.5, 948.5, 2400.6, 1760, 2983.43, 480.4,  1250.45, 75.29,1045.6]})----result = df.groupby(pd.cut(df['salesman_id'], bins=[0,5006,np.inf],  labels=['S1', 'S2']))['sale_jan'].sum().reset_index()**

**Ques:-30.** Write a Pandas program to split the following dataset using group by on first column and aggregate over multiple lists on second column.

**Ans:- df = pd.DataFrame({'student_id': ['S001','S001','S002','S002','S003','S003'],'marks': [[88,89,90],[78,81,60],[84,83,91],[84,88,91],[90,89,92],[88,59,90]]})---->result = df.set_index('student_id')['marks'].groupby('student_id').apply(list).apply(lambda x: np.mean(x,0))**

**Ques:-31.** Write a Pandas program to split the following dataset using group by on 'salesman_id' and find the first order date for each group.

**Ans:- result = df.groupby('salesman_id')['ord_date'].min()**





In [10]:
# Ques-32. Write a Pandas program to split a given dataset using group by on multiple columns and drop last n rows of from each group.

pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
df = pd.DataFrame({
'ord_no':[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10','2012-10-05','2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3002,3001,3004,3003,3002,3003,3001],
'salesman_id':[5002,5003,5001,5003,5002,5001,5001,5003,5003,5002,5003,5001]})
print("Original Orders DataFrame:")
print(df)
print("\nSplit the said data on 'salesman_id', 'customer_id' wise:")
result = df.groupby(['salesman_id', 'customer_id'])
for name,group in result:
    print("\nGroup:")
    print(name)
    print(group)
n = 2
#result1 = df.groupby(['salesman_id', 'customer_id']).tail(n).index, axis=0)
print("\nDroping last two records:")
result1 = df.drop(df.groupby(['salesman_id', 'customer_id']).tail(n).index, axis=0)
print(result1)

Original Orders DataFrame:
    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3002         5002
1    70009     270.65  2012-09-10         3001         5003
2    70002      65.26  2012-10-05         3001         5001
3    70004     110.50  2012-08-17         3003         5003
4    70007     948.50  2012-09-10         3002         5002
5    70005    2400.60  2012-07-27         3002         5001
6    70008    5760.00  2012-09-10         3001         5001
7    70010    1983.43  2012-10-10         3004         5003
8    70003    2480.40  2012-10-10         3003         5003
9    70012     250.45  2012-06-27         3002         5002
10   70011      75.29  2012-08-17         3003         5003
11   70013    3045.60  2012-04-25         3001         5001

Split the said data on 'salesman_id', 'customer_id' wise:

Group:
(5001, 3001)
    ord_no  purch_amt    ord_date  customer_id  salesman_id
2    70002      65.26  2012-10-05         3001       

#**Pandas Handling Missing Values-**

In [11]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
df = pd.DataFrame({
'ord_no':[70001,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001],
'salesman_id':[5002,5003,5001,np.nan,5002,5001,5001,np.nan,5003,5002,5003,np.nan]})
print("Original Orders DataFrame:")
print(df)

Original Orders DataFrame:
     ord_no  purch_amt    ord_date  customer_id  salesman_id
0   70001.0     150.50  2012-10-05         3002       5002.0
1       NaN     270.65  2012-09-10         3001       5003.0
2   70002.0      65.26         NaN         3001       5001.0
3   70004.0     110.50  2012-08-17         3003          NaN
4       NaN     948.50  2012-09-10         3002       5002.0
5   70005.0    2400.60  2012-07-27         3001       5001.0
6       NaN    5760.00  2012-09-10         3001       5001.0
7   70010.0    1983.43  2012-10-10         3004          NaN
8   70003.0    2480.40  2012-10-10         3003       5003.0
9   70012.0     250.45  2012-06-27         3002       5002.0
10      NaN      75.29  2012-08-17         3001       5003.0
11  70013.0    3045.60  2012-04-25         3001          NaN


**Ques:-1.**Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

**Ans:- df.isna()**

**Ques:-2.** Write a Pandas program to identify the column(s) of a given DataFrame which have at least one missing value.

**Ans:- df.isna().any()**

**Ques:-3.** Write a Pandas program to count the number of missing values in each column of a given DataFrame.

**Ans:- df.isna().sum()**



In [12]:
# **Ques:-4.** Write a Pandas program to find and replace the missing values in a given DataFrame which do not have any valuable information.

# Ans:-

import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
df = pd.DataFrame({
'ord_no':[70001,np.nan,70002,70004,np.nan,70005,"--",70010,70003,70012,np.nan,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,"?",12.43,2480.4,250.45, 3045.6],
'ord_date': ['?','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,"--",3002,3001,3001],
'salesman_id':[5002,5003,"?",5001,np.nan,5002,5001,"?",5003,5002,5003,"--"]})
print("Original Orders DataFrame:")
print(df)
print("\nReplace the missing values with NaN:")
result = df.replace({"?": np.nan, "--": np.nan})
print(result)


Original Orders DataFrame:
   ord_no purch_amt    ord_date customer_id salesman_id
0   70001     150.5           ?        3002        5002
1     NaN    270.65  2012-09-10        3001        5003
2   70002     65.26         NaN        3001           ?
3   70004     110.5  2012-08-17        3003        5001
4     NaN     948.5  2012-09-10        3002         NaN
5   70005    2400.6  2012-07-27        3001        5002
6      --      5760  2012-09-10        3001        5001
7   70010         ?  2012-10-10        3004           ?
8   70003     12.43  2012-10-10          --        5003
9   70012    2480.4  2012-06-27        3002        5002
10    NaN    250.45  2012-08-17        3001        5003
11  70013    3045.6  2012-04-25        3001          --

Replace the missing values with NaN:
     ord_no  purch_amt    ord_date  customer_id  salesman_id
0   70001.0     150.50         NaN       3002.0       5002.0
1       NaN     270.65  2012-09-10       3001.0       5003.0
2   70002.0      65.26  

**Ques:-5.** Write a Pandas program to drop the rows where at least one element is missing in a given DataFrame.

**Ans:- result = df.dropna()**

**Ques:-6.** Write a Pandas program to drop the columns where at least one element is missing in a given DataFrame

**Ans:- result = df.dropna(axis='columns')**



In [13]:
#Ques:-7. Write a Pandas program to drop the rows where all elements are missing in a given DataFrame.

pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
df = pd.DataFrame({
'ord_no':[np.nan,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'purch_amt':[np.nan,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': [np.nan,'2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[np.nan,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001]})

print("Original Orders DataFrame:")
print(df)
print("\nDrop the rows where all elements are missing:")
result = df.dropna(how='all')
print(result)

Original Orders DataFrame:
     ord_no  purch_amt    ord_date  customer_id
0       NaN        NaN         NaN          NaN
1       NaN     270.65  2012-09-10       3001.0
2   70002.0      65.26         NaN       3001.0
3   70004.0     110.50  2012-08-17       3003.0
4       NaN     948.50  2012-09-10       3002.0
5   70005.0    2400.60  2012-07-27       3001.0
6       NaN    5760.00  2012-09-10       3001.0
7   70010.0    1983.43  2012-10-10       3004.0
8   70003.0    2480.40  2012-10-10       3003.0
9   70012.0     250.45  2012-06-27       3002.0
10      NaN      75.29  2012-08-17       3001.0
11  70013.0    3045.60  2012-04-25       3001.0

Drop the rows where all elements are missing:
     ord_no  purch_amt    ord_date  customer_id
1       NaN     270.65  2012-09-10       3001.0
2   70002.0      65.26         NaN       3001.0
3   70004.0     110.50  2012-08-17       3003.0
4       NaN     948.50  2012-09-10       3002.0
5   70005.0    2400.60  2012-07-27       3001.0
6       NaN   

**Ques:-8.** Write a Pandas program to keep the rows with at least 2 NaN values in a given DataFrame.

**Ans:- result = df.dropna(thresh=2)**

**Ques:-9.** Write a Pandas program to drop those rows from a given DataFrame in which specific columns have missing values.

**Ans:- result = df.dropna(subset=['ord_no', 'customer_id'])**

**Ques:-10.** Write a Pandas program to keep the valid entries of a given DataFrame.

**Ans:- result = df.dropna(inplace=False)**----keep only those rows which has no null values

**Ques:-11.** Write a Pandas program to calculate the total number of missing values in a DataFrame.

**Ans:- result = df.isna().sum().sum()**

**Ques:-12.** Write a Pandas program to replace NaNs with a single constant value in specified columns in a DataFrame.

**Ans:- result = df['ord_no'].fillna(0, inplace=False)**

**Ques:-13.** Write a Pandas program to replace NaNs with the value from the previous row or the next row in a given DataFrame.

**Ans:-** Replacing NaNs with the value from the previous row (purch_amt)---**df['purch_amt'].fillna(method='pad', inplace=True)**-----Replacing NaNs with the value from the next row (sale_amt)---**df['sale_amt'].fillna(method='bfill', inplace=True)**

**Ques:-14.** Write a Pandas program to replace NaNs with median or mean of the specified columns in a given DataFrame.

**Ans:- df['purch_amt'].fillna(df['purch_amt'].median(), inplace=True)---->df['sale_amt'].fillna(int(df['sale_amt'].mean()), inplace=True)**

**Ques:-15.** Write a Pandas program to interpolate the missing values using the Linear Interpolation method in a given DataFrame.

linear interpolation is a method of curve fitting using linear polynomials to construct new data points within the range of a discrete set of known data points

**Ans:- df['purch_amt'].interpolate(method='linear', direction = 'forward', inplace=True)**

**Ques:-16.** Write a Pandas program to count the number of missing values of a specified column in a given DataFrame.

**Ans:- result = df['purch_amt'].value_counts(dropna=False).loc[np.nan]**

**Ques:-18.** Write a Pandas program to find the Indexes of missing values in a given DataFrame.

**Ans:- result = df['ord_no'].isnull().to_numpy().nonzero()**

**Ques:-19.** Write a Pandas program to replace the missing values with the most frequent values present in each column of a given DataFrame.

**Ans:- result = df.fillna(df.mode().iloc[0])**

**Ques:-20.** Write a Pandas program to create a hitmap for more information about the distribution of missing values in a given DataFrame.

**Ans:-plt.figure(figsize=(16,10))----sns.heatmap(df.isnull(), cbar=False, cmap="YlGnBu")---plt.show()**